### ISSUE TITLE
Using in Grid Row Editor (datecolumn)

### ISSUE THREAD

**Issue by ex7r3me** [behrang/Ext.ux.JalaliDatePlugin#2]
Hi , thanks a lot for this plugin 
I have a grid with a date column , after editing grid's row with roweditor plugin (i've used jalali plugin with editor) after click on update it convert jalali date to Georgian. How can I use jalali date with grid row editor ?

**Comment by behrang** [comment]
This plugin only changes the display of the date picker. Undr the hood, the selected date value is an instance of Date object. So, if you want to have a Jalali string of that value, you have to convert it manually.

There is a formatter you can use for this purpose:

```
var jalalyFormatted = Ext.Date.format(value, 'Jalali');
```
